# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('cookie_id', models.CharField(max_length=64)),
                ('code', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.Inbox')),
            ],
        ),
    ]
