# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('poster_id', models.IntegerField()),
                ('cookie_id', models.CharField(max_length=6)),
                ('image', models.CharField(blank=True, db_column='image_id', max_length=12, null=True)),
                ('root_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('title', models.CharField(db_column='title_id', max_length=255, null=True)),
                ('datetime', models.IntegerField()),
                ('rating', models.SmallIntegerField()),
                ('picrand', models.SmallIntegerField()),
                ('tcrc', models.IntegerField()),
                ('captxt', models.CharField(max_length=16)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
