# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('text_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('entry_id', models.IntegerField()),
                ('datetime', models.IntegerField()),
                ('x_size', models.SmallIntegerField()),
                ('y_size', models.SmallIntegerField()),
                ('extension', models.CharField(max_length=5, db_column='extencion')),
                ('md5sum', models.CharField(max_length=32)),
                ('img_hash', models.CharField(editable=False, max_length=255, null=True)),
                ('no_big_image', models.IntegerField(blank=True, null=True)),
                ('poster_ip', models.CharField(max_length=23)),
                ('uses', models.IntegerField()),
            ],
            options={'db_table': 'images'}
        ),
    ]
