# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0002_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_hash',
            field=models.CharField(max_length=255, null=True, editable=False),
        ),
    ]
