# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-19 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0003_recreate_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dont_raise',
            field=models.BooleanField(default=False),
        ),
    ]
