# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0004_auto_20170121_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenta',
            name='rating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
