# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0005_lenta_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenta',
            name='rating',
            field=models.IntegerField(db_index=True, default=0, editable=False),
        ),
    ]
