# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0006_auto_20170121_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenta',
            name='datetime',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lenta',
            name='drowner',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lenta',
            name='hidden',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lenta',
            name='sticker',
            field=models.SmallIntegerField(db_index=True),
        ),
    ]
