# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0008_auto_20170121_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedCookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(db_index=True, max_length=64)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='cookie_id',
            field=models.CharField(max_length=64),
        ),
    ]
