# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapa', '0005_randomlogo'),
        ('apa', '0009_auto_20170121_2220'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='lenta',
            index_together=set([('drowner', 'hidden', 'category'), ('drowner', 'hidden', 'rating'), ('drowner', 'hidden', 'datetime'), ('drowner', 'hidden')]),
        ),
    ]
