# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0010_auto_20170122_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.SmallIntegerField(db_index=True),
        ),
    ]
