# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0011_auto_20170122_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('image_name', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=32)),
                ('image_id', models.CharField(editable=False, max_length=12)),
                ('last_updated', models.IntegerField()),
                ('num_used', models.IntegerField()),
            ],
            options={
                'db_table': 'capture',
                'managed': False,
            },
        ),
    ]
