# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 17:37
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0012_captcha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captcha',
            options={},
        ),
        migrations.AddField(
                model_name='captcha',
                name='image_file',
                field=models.ImageField(upload_to='capture/base/', null=True),
                preserve_default=False,
        ),
    ]
