# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 18:10
from __future__ import unicode_literals

import os

from django.conf import settings
from django.db import migrations


def convert_captcha_files(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Captcha = apps.get_model("apa", "Captcha")
    for cap in Captcha.objects.filter(image_file__isnull=True):
        cap.image_file = os.path.join('capture', 'base', cap.image_name)
        cap.save()
        

def back_noop(apps, schema_editor):
    Captcha = apps.get_model("apa", "Captcha")
    Captcha.objects.all().update(image_file=None)


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0013_auto_20170212_1737'),
    ]

    operations = [
        migrations.RunPython(convert_captcha_files, back_noop),
    ]
