# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0014_auto_20170212_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='image_id',
            field=models.CharField(editable=False, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='image_name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='last_updated',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='captcha',
            name='num_used',
            field=models.IntegerField(editable=False),
        ),
    ]
