# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 20:29
from __future__ import unicode_literals

import datetime

from django.db import migrations

from apa.utils import to_datetime


def ban_scripts(apps, schema_editor):
    Comment = apps.get_model("apa", "Comment")
    Lenta = apps.get_model("apa", "Lenta")
    BannedCookie = apps.get_model("apa", "BannedCookie")

    week_ago = to_datetime(datetime.datetime.now() - datetime.timedelta(7))
    all_comments = Comment.objects.filter(datetime__gte=week_ago)
    all_cnt = all_comments.count()
    for i,c in enumerate(all_comments):
        ct = c.text.lower()
        if any(t in ct for t in ["<script", "<link", "<style"]):
            c.deleted = 1
            c.save()

            BannedCookie.objects.get_or_create(cookie_id=c.cookie_id)
            
            Lenta.objects.filter(root_id=c.pk).update(hidden=1, drowner=1)
            
        if i % 100 == 0:
            print "Done %s of %s" % (i, all_cnt)


class Migration(migrations.Migration):

    dependencies = [
        ('apa', '0016_auto_20170302_2029'),
    ]

    operations = [
        migrations.RunPython(ban_scripts),
    ]


