# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-19 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapa', '0008_auto_20170219_1557'),
        ('apa', '0018_comment_source'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='lenta',
            index_together=set([('drowner', 'hidden', 'category', 'sticker', 'datetime'), ('drowner', 'hidden', 'category'), ('drowner', 'hidden', 'rating'), ('drowner', 'hidden', 'datetime'), ('drowner', 'hidden')]),
        ),
    ]
