# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('canceled', models.BooleanField(default=False)),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('new_cat', models.IntegerField()),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karma.Wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
