# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 21:35
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def update_rating(apps, schema_editor):
    Comment = apps.get_model("apa", "Comment")
    LikeTransaction = apps.get_model("karma", "LikeTransaction")
    
    for lt in LikeTransaction.objects.all():
        Comment.objects.filter(comment_id=lt.comment_id, deleted=False).update(rating=F('rating') + 1)


class Migration(migrations.Migration):

    dependencies = [
        ('karma', '0002_cattransaction'),
    ]

    operations = [
        migrations.RunPython(update_rating),
    ]


