# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-13 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('number', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(db_index=True, max_length=64)),
                ('comment_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(db_index=True, max_length=64)),
                ('comment_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('comment_id', models.CharField(max_length=64)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RandomLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='random/logos/')),
            ],
        ),
        migrations.CreateModel(
            name='RandomPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RandomPackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='random/new/')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newapa.RandomPack')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=set([('cookie_id', 'comment_id')]),
        ),
    ]
