# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=25)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='randompackimage',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='newapa.RandomPack'),
        ),
    ]
