# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapa', '0002_auto_20170117_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
