# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapa', '0003_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
