# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapa', '0007_moderationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie_id', models.CharField(db_index=True, max_length=64)),
                ('comment_id', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=set([('cookie_id', 'comment_id')]),
        ),
    ]
